os:
  - linux
  - osx
language:
  - go
  - ruby
go: "1.12"

if: (tag =~ ^v) OR (tag =~ ^test) OR (branch = master) OR (branch == test)

env:
  global:
    - GO111MODULE=on
    - NAME=v2raya
    - VERSION=$(git describe --abbrev=0 --tags)
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
      - reprepro
      - gnupg
      - gnupg2
      - expect

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get github.com/mitchellh/gox ;fi
  - gem install fpm
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd service && gox -osarch="linux/amd64 linux/arm" -mod=vendor -ldflags="-X V2RayA/global.Version=${VERSION:1}" && cp -r V2RayA_* ../ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then files="V2RayA_linux_amd64=/usr/bin/v2raya install/v2raya.service=/etc/systemd/system/v2raya.service" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then params="-f -n $NAME -v ${VERSION:1} --after-install install/after_install.sh --before-remove install/before_remove.sh --after-remove install/after_remove.sh --after-upgrade install/after_upgrade.sh $files" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then fpm -s dir -t deb -p v2raya_debian.deb $params && fpm -s dir -t rpm -p v2raya_redhat.rpm $params && fpm -s dir -t pacman -p v2raya_arch.pkg.tar.xz $params && fpm -s dir -t freebsd -p v2raya_freebsd.txz $params ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd service && CGO_ENABLED=0 go build -mod=vendor -a -ldflags='-extldflags "-static" -X global.Version=${VERSION:1}' -o v2raya && cp v2raya ../V2RayA_darwin_amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo -E fpm -s dir -t osxpkg -p v2raya_osx.pkg $params ; fi

before_deploy:
  - mkdir -p apt/incoming && cp -r install/key install/conf apt/
  - cd apt
  - gpg2 --import key/public-key.asc
  - ../install/gpg2_expect --allow-secret-key-import --import ../install/private-key.asc
  - ../install/reprepro_expect --ask-passphrase -Vb . export
  - ../install/reprepro_expect --ask-passphrase -Vb . includedeb v2raya ../v2raya_debian.deb

deploy:
  - provider: releases
    api_key:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    file:
      - "V2RayA_darwin_amd64"
      - "V2RayA_linux_amd64"
      - "V2RayA_linux_arm"
      - "v2raya_debian.deb"
      - "v2raya_freebsd.txz"
      - "v2raya_redhat.rpm"
      # - "v2raya_osx.pkg"
      - "v2raya_arch.pkg.tar.xz"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
    keep_history: true
    target_branch: apt
    local_dir: apt/
    on:
      tags: true
