os:
  - linux
  - osx
language: go
go: "1.12"

if: (tag =~ ^v) OR (branch = master)

env:
  global:
    - GO111MODULE=on
    - NAME=v2raya
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
      - perl
  homebrew:
    packages:
      - perl

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get github.com/mitchellh/gox ;fi
  - gem install fpm
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd service && VERSION=$(git describe --abbrev=0 --tags) && gox -osarch="linux/amd64 linux/arm" -mod=vendor -ldflags="-X global.Version=${VERSION:1}" && cp -r V2RayA_* ../ && cp -r V2RayA_linux_amd64 v2raya ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp -f V2RayA_linux_amd64 v2raya && fpm -s dir -t deb -n $NAME -v ${VERSION:1} --prefix /usr/bin v2raya && fpm -s dir -t rpm -n $NAME -v ${VERSION:1} --prefix /usr/bin v2raya && fpm -s dir -t pacman -n $NAME -v ${VERSION:1} --prefix /usr/bin v2raya && fpm -s dir -t freebsd -n $NAME -v ${VERSION:1} --prefix /usr/bin v2raya ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv *.deb ../v2raya_debian.deb ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv *.txz ../v2raya_freebsd.txz ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv *.rpm ../v2raya_redhat.rpm ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv *.pkg.tar.xz ../v2raya.pkg.tar.xz ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd service && CGO_ENABLED=0 go build -mod=vendor -a -ldflags='-extldflags "-static" -X global.Version=${VERSION:1}' -o v2raya && cp v2raya ../V2RayA_darwin_amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo -E fpm -s dir -t osxpkg -n $NAME -v ${VERSION:1} --prefix /usr/bin v2raya ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv *.pkg ../v2raya_macos.pkg ;fi

deploy:
  provider: releases
  api_key:
    secure: dI7F0zR8lks/+Nk1RZ41V8jidKSXJRDkUFhjRkQFLO3NE2wCwlftSCEMhRa0ULqyskCmboKmVAAbCZupttFynWaj9ttpa2UWng+EfNtwEOvB0wp8b2CCV13Y/ncvaofIULWGJsjNbPAILkMp4YTfs92GslxGcLAJqAL3/P7O3Tx8AO7l7WzkVOC31sO5ZApb4kzb58T5IWY7mDZ9gSvjC4iyBGMwFG8YZXmknxTHVsDNWXvZwmScDB3VTu+X6U3aEVvdOYlmcqxDOzc8ZFGSpw6R4Dy2/KUH99UtofrF/buQauPmUq8Znu8u0LePtNI9ePxACqokPo8e+4MyE1ipVgoirgZmS2ICLnXTsSrwmNQ8S3+alOZW/+Kfo1v9Besfia9DoWUxOinRlGLVmnWFbMasRxKsqLfR2q3rSpWU4cKbH5WpxHewBnYqa86Xwp9G2O4MLpe6Ct7MLOiLonBXnUb2hXZGri8y87lTAUugxj/wSqXucw5SSDbRJT9v6Zwk5Eaj7Fc8QNTt7eqhVvmE8UucQPy1TL3gkTYFtUDkngWV0d0Y4JOHQW4ZUd28WLWIEyFoLZ8ZUT/kx87E69BhsqTq5S6tFRmWUXNLUpSrxJq29UdFy6zgNJhxgxxXXVpUH6wYHqV7nDCsZygJ5Z+iTTbkt+e1bIkhXbf/fM4+Yws=
  file:
    - "V2RayA_darwin_amd64"
    - "V2RayA_linux_amd64"
    - "V2RayA_linux_arm"
    - "v2raya_debian.deb"
    - "v2raya_freebsd.txz"
    - "v2raya_redhat.rpm"
    - "v2raya_macos.pkg"
    - "v2raya_arch.pkg.tar.xz"
  skip_cleanup: true
  # overwrite: true
  on:
    tags: true

    