version: "3"
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 2017:2017
    volumes:
      - shared-data:/etc/v2ray
      - ./service:/service:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev/net:/dev/net
    environment:
      - REDIS=redis:6379
    links:
      - redis

  v2ray:
    restart: always
    image: "v2ray/official"
    pid: service:backend
    environment:
     - V2RAY_LOCATION_ASSET=/etc/v2ray
    ports:
      - 20170-20172:20170-20172
    volumes:
      - shared-data:/etc/v2ray
    entrypoint: sh -c "cp -rfu /usr/bin/v2ray/*.dat /etc/v2ray && v2ray -config=/etc/v2ray/config.json"
  
  redis:
    restart: always
    image: "redislabs/rejson:latest"

volumes:
  shared-data:
